"""
Emits Pine overlay(s) that shade every bar inside an HTF scanner streak for the ticker on the
chart. Each return window (1M / 3M / 6M) gets its own color layer (aqua / fuchsia / yellow);
overlapping windows blend since the layers stack. Includes a bottom-left legend table, and
per-window 1/0 flags exposed via display.data_window for hover lookup.

Sources: one review CSV per window (status == OK rows, i.e. the "Data Filtered" set). One
range per row: first_qualifying_date .. last_qualifying_date. Windows whose CSV doesn't exist
yet are skipped, so this runs fine with just 1M.

Encoding, per ticker:  ";AA:210303-210513,220121-220404|230101-230301|"
The three pipe-separated fields are 1M | 3M | 6M ranges (empty if none). YYMMDD dates.

Pine constraints that shaped the script (all hit for real on 2026-09-18): "The if statement
is too long" fires when a big string constant is inlined into ANY conditional, and `var x =
expr` is a hidden conditional. So the data is only touched by plain top-level statements,
one ~3 KB literal each, and only the small per-ticker segment reaches the cached arrays.
Scripts are split alphabetically by --max-kb; add them all, only the matching one draws.

    python generate_scanner_days.py
    python generate_scanner_days.py --max-kb 40
"""
import argparse
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
HTF = os.path.join(HERE, "..")

WINDOWS = ["1m", "3m", "6m"]
SOURCES = {
    "1m": os.path.join(HTF, "htf_1m_flag_review_v2_flagpole_bucketed.csv"),
    "3m": os.path.join(HTF, "htf_3m_flag_review_v2_flagpole_bucketed.csv"),
    "6m": os.path.join(HTF, "htf_6m_flag_review_v2_flagpole_bucketed.csv"),
}

PIECE = 3000  # max chars per string literal; split only at ticker boundaries


def yymmdd(s: str) -> str:
    y, m, d = s.split("-")
    return f"{y[2:]}{m}{d}"


def load_ranges(path: str) -> dict:
    df = pd.read_csv(path)
    ok = df[df["status"] == "OK"].sort_values(["revised_ticker", "first_qualifying_date"])
    out = {}
    for row in ok.itertuples():
        out.setdefault(row.revised_ticker, []).append(
            f"{yymmdd(row.first_qualifying_date)}-{yymmdd(row.last_qualifying_date)}"
        )
    return out


def encode_ticker(tkr: str, per_window: dict) -> str:
    fields = [",".join(per_window.get(w, {}).get(tkr, [])) for w in WINDOWS]
    return f";{tkr}:" + "|".join(fields)


def split_pieces(data: str) -> list:
    segs = [";" + s for s in data.split(";") if s]
    pieces, cur = [], ""
    for s in segs:
        if cur and len(cur) + len(s) > PIECE:
            pieces.append(cur)
            cur = ""
        cur += s
    if cur:
        pieces.append(cur)
    return pieces


def pine(title: str, data: str) -> str:
    pieces = split_pieces(data)
    n = len(pieces)
    decls = "\n".join(f'D{i} = "{p}"' for i, p in enumerate(pieces))
    finds = "\n".join(f"s{i} = cut(D{i}, key)" for i in range(n))
    joined = " + ".join(f"s{i}" for i in range(n))
    return f'''//@version=6
// {title} -- GENERATED by generate_scanner_days.py; edit that, not this.
// Shades bars inside HTF scanner streaks for the ticker on the chart. Opacity steps with
// how many return windows (1M/3M/6M) had it on the scanner that day. Add every generated
// script; only the one holding this ticker draws anything.
//
// No string constant may reach an `if` or a `var` initializer (Pine: "The if statement is
// too long"). Data is touched only by plain top-level statements, one literal each.
indicator("{title}", overlay = true)

{decls}

color1m = input.color(color.aqua, "1M Color")
color3m = input.color(color.fuchsia, "3M Color")
color6m = input.color(color.yellow, "6M Color")
layerTransparency = input.int(80, "Layer Transparency", minval = 0, maxval = 100, tooltip = "Applied per window layer; overlapping windows blend since each layer is drawn on top of the last")

// Returns this ticker's "1m|3m|6m" body from one piece, or "" if not in it.
cut(string src, string k) =>
    p = str.pos(src, k)
    rest = na(p) ? "" : str.substring(src, p + str.length(k))
    q = str.pos(rest, ";")
    na(q) ? rest : str.substring(rest, 0, q)

key = ";" + syminfo.ticker + ":"
{finds}
seg = {joined}
segp = seg == "" ? "||" : seg   // absent ticker still yields three empty fields

// Appending "-" guarantees split yields >= 2 elements; an empty field pushes one na pair
// that never matches. Keeps this free of `if`.
fill(string s, int[] rs, int[] re) =>
    parts = str.split(s, ",")
    j = 0
    while j < array.size(parts)
        r = str.split(array.get(parts, j) + "-", "-")
        array.push(rs, int(str.tonumber(array.get(r, 0))))
        array.push(re, int(str.tonumber(array.get(r, 1))))
        j += 1

var int[] rs1 = array.new<int>()
var int[] re1 = array.new<int>()
var int[] rs3 = array.new<int>()
var int[] re3 = array.new<int>()
var int[] rs6 = array.new<int>()
var int[] re6 = array.new<int>()
var bool parsed = false
while not parsed
    parsed := true
    ws = str.split(segp, "|")
    fill(array.get(ws, 0), rs1, re1)
    fill(array.get(ws, 1), rs3, re3)
    fill(array.get(ws, 2), rs6, re6)

hit(int[] rs, int[] re, int d) =>
    h = false
    i = 0
    while i < array.size(rs)
        h := h or (d >= array.get(rs, i) and d <= array.get(re, i))
        i += 1
    h

d = (year % 100) * 10000 + month * 100 + dayofmonth
hit1m = hit(rs1, re1, d)
hit3m = hit(rs3, re3, d)
hit6m = hit(rs6, re6, d)

bgcolor(hit1m ? color.new(color1m, layerTransparency) : na)
bgcolor(hit3m ? color.new(color3m, layerTransparency) : na)
bgcolor(hit6m ? color.new(color6m, layerTransparency) : na)

// Pine has no way to react to mouse/crosshair position or render text that only appears on
// hover -- scripts only ever see the bar data, never UI state. This is the closest real
// equivalent: hidden from the chart/scale (display.data_window only), so hovering any bar
// shows these three 0/1 flags in TradingView's own Data Window panel.
plot(hit1m ? 1 : 0, title = "1M hit", display = display.data_window)
plot(hit3m ? 1 : 0, title = "3M hit", display = display.data_window)
plot(hit6m ? 1 : 0, title = "6M hit", display = display.data_window)

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//// LEGEND
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Legend text colors are deliberately NOT the actual (heavily transparent) on-chart swatch
// colors -- at high layerTransparency those are too washed out to read as text. Single-window
// entries use the pure input color; overlap entries blend the two pure colors at a fixed,
// legend-only mix so they stay bright regardless of layerTransparency.
blend(base, fg, transp) =>
    a = (100 - transp) / 100.0
    r = math.round(color.r(base) * (1 - a) + color.r(fg) * a)
    g = math.round(color.g(base) * (1 - a) + color.g(fg) * a)
    b = math.round(color.b(base) * (1 - a) + color.b(fg) * a)
    color.rgb(r, g, b)

legendMix = 50
lc1m3m = blend(color1m, color3m, legendMix)
lc1m6m = blend(color1m, color6m, legendMix)
lc3m6m = blend(color3m, color6m, legendMix)
lcAll  = blend(lc1m3m, color6m, legendMix)

var table legend = table.new(
     position.bottom_left,
     4,
     3,
     bgcolor = color.new(color.white, 100),
     border_width = 0
 )

if barstate.islast
    table.cell(legend, 0, 0, "1M only", text_color = color1m, text_size = size.normal)
    table.cell(legend, 1, 0, "3M only", text_color = color3m, text_size = size.normal)
    table.cell(legend, 2, 0, "6M only", text_color = color6m, text_size = size.normal)
    table.cell(legend, 3, 0, "1M+3M+6M", text_color = lcAll, text_size = size.normal)
    table.cell(legend, 0, 1, "1M+3M", text_color = lc1m3m, text_size = size.normal)
    table.cell(legend, 1, 1, "1M+6M", text_color = lc1m6m, text_size = size.normal)
    table.cell(legend, 2, 1, "3M+6M", text_color = lc3m6m, text_size = size.normal)
    table.cell(legend, 0, 2, " ", text_color = color.new(color.white, 100))
    table.cell(legend, 1, 2, " ", text_color = color.new(color.white, 100))
    table.cell(legend, 2, 2, " ", text_color = color.new(color.white, 100))
    table.merge_cells(legend, 3, 0, 3, 1)
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-kb", type=float, default=25.0, help="max data per script")
    args = ap.parse_args()

    per_window = {}
    for w in WINDOWS:
        path = SOURCES[w]
        if os.path.exists(path):
            per_window[w] = load_ranges(path)
            print(f"{w}: {sum(len(v) for v in per_window[w].values()):,} ranges, "
                  f"{len(per_window[w]):,} tickers")
        else:
            print(f"{w}: no review CSV yet at {os.path.basename(path)} -- skipped")

    tickers = sorted(set().union(*(set(d) for d in per_window.values())))

    limit = int(args.max_kb * 1024)
    chunks, cur, cur_first, cur_last = [], "", None, None
    for tkr in tickers:
        seg = encode_ticker(tkr, per_window)
        if cur and len(cur) + len(seg) > limit:
            chunks.append((cur_first, cur_last, cur))
            cur, cur_first = "", None
        if cur_first is None:
            cur_first = tkr
        cur += seg
        cur_last = tkr
    if cur:
        chunks.append((cur_first, cur_last, cur))

    for old in os.listdir(HERE):
        if old.startswith("htf_scanner_days_") and old.endswith(".pine"):
            os.remove(os.path.join(HERE, old))

    for first, last, data in chunks:
        title = f"HTF Scanner Days {first}-{last}"
        fname = f"htf_scanner_days_{first}_{last}.pine"
        with open(os.path.join(HERE, fname), "w", encoding="utf-8") as f:
            f.write(pine(title, data))
        print(f"{fname:45s} {len(data)/1024:6.1f} KB")

    print(f"\n{len(tickers):,} tickers -> {len(chunks)} script(s)")


if __name__ == "__main__":
    main()
